# Generated by Django 5.2.9 on 2026-06-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('aplica_a', models.CharField(choices=[('TODOS', 'Todos los aspirantes'), ('INDICE_EQUIVALENTE', 'Solo si requiere índice académico equivalente')], default='TODOS', max_length=30)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_pasaporte', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('programa_postgrado', models.CharField(blank=True, max_length=200)),
                ('centro_regional', models.CharField(blank=True, max_length=150)),
                ('universidad_origen', models.CharField(choices=[('UTP', 'Universidad Tecnológica de Panamá'), ('OTRA', 'Otra universidad')], default='UTP', max_length=10)),
                ('nombre_universidad_origen', models.CharField(blank=True, max_length=200)),
                ('sistema_calificacion_diferente', models.BooleanField(default=False, help_text='Marcar si la universidad de origen usa un sistema de calificación distinto al de la UTP.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace_url', models.URLField(blank=True, help_text='Enlace compartido del documento. Ejemplo: Google Drive, OneDrive, Dropbox.', max_length=1000)),
                ('estado', models.CharField(choices=[('SIN_ENVIAR', 'Sin enviar'), ('EN_REVISION', 'En revisión'), ('EN_PROCESO', 'En proceso'), ('SUBSANAR', 'Subsanar'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='SIN_ENVIAR', max_length=20)),
                ('observacion_admin', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='admisiones.requirement')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='admisiones.studentprofile')),
            ],
            options={
                'ordering': ['requirement__orden'],
                'unique_together': {('profile', 'requirement')},
            },
        ),
    ]
