# Generated by Django 5.2.9 on 2026-06-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('FACULTAD', 'Facultad'), ('CENTRO_REGIONAL', 'Centro Regional')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Facultad o Centro Regional',
                'verbose_name_plural': 'Facultades y Centros Regionales',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='centro_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='admisiones.academicunit', verbose_name='Facultad o Centro Regional'),
        ),
        migrations.CreateModel(
            name='GraduateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='admisiones.academicunit')),
            ],
            options={
                'verbose_name': 'Programa de Postgrado',
                'verbose_name_plural': 'Programas de Postgrado',
                'ordering': ['unidad_academica__nombre', 'orden', 'nombre'],
                'unique_together': {('unidad_academica', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='programa_postgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='admisiones.graduateprogram', verbose_name='Programa de postgrado'),
        ),
    ]
